#mongo: 4.4 nếu có lỗi AVX

# version: '3.8'
#MongoDB 5.0+ requires a CPU with AVX support, => sử dụng image: mongo:4.4
services:
  #tên database
  db-mongo:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  be-nest:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: unless-stopped
    environment:
      - PORT=8080
      - NODE_ENV=production
      - MONGO_URL=mongodb://root:123456@db-mongo:27017/jilee?authSource=admin
      # - DB_HOST=host.docker.internal
    expose:
      - 8080
    ports:
      - 8080:8080

#phần volume này để khi chạy lại docker sẽ kh bị mất dữ liệu(database)
volumes:
  mongodb:

    #câu lệnh run: docker compose -p jilee-nest up -d
